# Generated by Django 5.0.7 on 2024-07-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_me',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hire_me',
            name='currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hire_me',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hire_me',
            name='post',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Full-time', 'Full-time'), ('Project-based', 'Project-based')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hire_me',
            name='recruiter_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hire_me',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hire_me',
            name='salary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
