# Generated by Django 5.0.7 on 2024-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_alter_hire_me_company_name_alter_hire_me_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire_me',
            name='pay_type',
            field=models.CharField(choices=[('/hr', '/hr'), ('/project', '/project'), ('salary', 'salary')], max_length=20, null=True),
        ),
    ]
